% Matlab Driver to integrate an ODE file generated by PottersWheel on 2021-02-18 12:52:28
%
% Model: PGE_mass20

%% Initial values
x0 = zeros(1, 37);
x0(  1) =          1; % IP
x0(  2) =       0.06; % EP3
x0(  3) =      0.034; % EP4
x0(  4) =      0.096; % DP1
x0(  5) =        0.1; % P2Y12
x0(  6) =          0; % P2Y12_act
x0(  7) =          0; % IP_act
x0(  8) =          0; % DP1_act
x0(  9) =          0; % DP1_BWA
x0( 10) =          0; % EP3_act
x0( 11) =          0; % EP3_L798
x0( 12) =          0; % EP4_act
x0( 13) =          0; % EP4_L161
x0( 14) =       0.59; % AC
x0( 15) =          0; % aAC
x0( 16) =          0; % Fors_AC
x0( 17) =        3.4; % cAMP
x0( 18) =          0; % AMP
x0( 19) =      10.34; % VASP
x0( 20) =          0; % pVASP
x0( 21) =       0.31; % PDE3
x0( 22) =          0; % aPDE3
x0( 23) =          0; % iPDE3
x0( 24) =      0.077; % PDE2
x0( 25) =       2.04; % PKA
x0( 26) =          0; % R
x0( 27) =          0; % C
x0( 28) =          0; % PKA_cAMP
x0( 29) =          0; % PKA_cAMP_cAMP
x0( 30) =          0; % PKA_cAMP_cAMP_cAMP
x0( 31) =          0; % PKA_cAMP_cAMP_cAMP_cAMP
x0( 32) =          0; % R_cAMP_cAMP
x0( 33) =          0; % PKA_cBIMPS
x0( 34) =          0; % PKA_cBIMPS_cBIMPS
x0( 35) =          0; % PKA_cBIMPS_cBIMPS_cBIMPS
x0( 36) =          0; % PKA_cBIMPS_cBIMPS_cBIMPS_cBIMPS
x0( 37) =          0; % R_cBIMPS_cBIMPS

%% xIDs
xIDs = {};
xIDs{end+1} = 'IP';
xIDs{end+1} = 'EP3';
xIDs{end+1} = 'EP4';
xIDs{end+1} = 'DP1';
xIDs{end+1} = 'P2Y12';
xIDs{end+1} = 'P2Y12_act';
xIDs{end+1} = 'IP_act';
xIDs{end+1} = 'DP1_act';
xIDs{end+1} = 'DP1_BWA';
xIDs{end+1} = 'EP3_act';
xIDs{end+1} = 'EP3_L798';
xIDs{end+1} = 'EP4_act';
xIDs{end+1} = 'EP4_L161';
xIDs{end+1} = 'AC';
xIDs{end+1} = 'aAC';
xIDs{end+1} = 'Fors_AC';
xIDs{end+1} = 'cAMP';
xIDs{end+1} = 'AMP';
xIDs{end+1} = 'VASP';
xIDs{end+1} = 'pVASP';
xIDs{end+1} = 'PDE3';
xIDs{end+1} = 'aPDE3';
xIDs{end+1} = 'iPDE3';
xIDs{end+1} = 'PDE2';
xIDs{end+1} = 'PKA';
xIDs{end+1} = 'R';
xIDs{end+1} = 'C';
xIDs{end+1} = 'PKA_cAMP';
xIDs{end+1} = 'PKA_cAMP_cAMP';
xIDs{end+1} = 'PKA_cAMP_cAMP_cAMP';
xIDs{end+1} = 'PKA_cAMP_cAMP_cAMP_cAMP';
xIDs{end+1} = 'R_cAMP_cAMP';
xIDs{end+1} = 'PKA_cBIMPS';
xIDs{end+1} = 'PKA_cBIMPS_cBIMPS';
xIDs{end+1} = 'PKA_cBIMPS_cBIMPS_cBIMPS';
xIDs{end+1} = 'PKA_cBIMPS_cBIMPS_cBIMPS_cBIMPS';
xIDs{end+1} = 'R_cBIMPS_cBIMPS';

[t,x] = ode15s(@PGE_ODE,[0 1500], x0);

figure(1)
subplot(1,1,1,'replace')
n = ceil(sqrt(length(x0)));
for i=1:length(x0)
    subplot(n, n, i);
    h = plot(t,x(:, i));
    title(strrep(xIDs{i}, '_', '\_'), 'FontSize', 8);
    set(gca, 'FontSize', 6);
end
