function dx = PGE_ODE(t, x)
% Matlab ODE file generated by PottersWheel on 2021-02-18 12:52:28
%
% Model: PGE_mass20

%% Driving input functions (all set to unit step function!)
u(1) = 0;
u(2) = 0.002;
u(3) = 0;
u(4) = 0;
u(5) = 2;
u(6) = 0;
u(7) = 0;
u(8) = 0;
u(9) = 0;
u(10) = 0;

%% Compartments
c(1) =          1; % cell

%% Parameters
k = zeros(37, 1);
k(  1) =     7.2663; % IP_activation_Ilo
k(  2) =  0.0303779; % DP1_activation_PGE
k(  3) =   0.153929; % DP1_inhibition
k(  4) =  0.0271071; % EP3_activation_PGE
k(  5) = 0.00867023; % EP3_activation_Sul
k(  6) =  0.0033158; % EP3_inhibition
k(  7) =  0.0113267; % EP4_activation_PGE
k(  8) = 9.5612e-05; % P2Y12_activation
k(  9) = 0.00436973; % EP4_inhibition
k( 10) =       5000; % ATP
k( 11) =    689.594; % AC_Vmax
k( 12) =      0.021; % AC_km
k( 13) =    113.577; % AC_k
k( 14) =  0.0718893; % PKA_AC
k( 15) =      1e-05; % Fors_cAMP
k( 16) =    1.83198; % IP_cAMP
k( 17) =    28.5001; % DP1_cAMP
k( 18) =    335.912; % EP3_cAMP
k( 19) =    293.316; % EP4_cAMP
k( 20) =     18.294; % P2Y12_cAMP
k( 21) =  0.0376551; % pVASP_k
k( 22) =        6.1; % PDE3_Vmax
k( 23) =        0.2; % PDE3_km
k( 24) =        120; % PDE2_Vmax
k( 25) =         50; % PDE2_km
k( 26) = 0.00496388; % aPDE3_k
k( 27) = 0.00636499; % iPDE3_k
k( 28) =       19.6; % PKA_Vmax
k( 29) =       17.4; % PKA_km
k( 30) =    1915.46; % PKA_cAMPgain
k( 31) =    8651.36; % PKA_cAMPloss
k( 32) =  0.0110836; % PKA_diss
k( 33) =    0.61518; % PKA_RcAMPdiss
k( 34) =    19403.9; % PKA_ass
k( 35) = 5.83103e-05; % PKA_cBIMPSgain
k( 36) = 0.00356233; % PKA_cBIMPSloss
k( 37) = 0.00476326; % PKA_RcBIMPSdiss

%% ODE:
dx = zeros(37, 1);
dx( 1) = -k(1)*x(1)*u(2); % IP
dx( 2) = -k(4)*x(2)*u(1)-k(5)*x(2)*u(7)-k(6)*x(2)*u(6); % EP3
dx( 3) = -k(7)*x(3)*u(1)-k(9)*x(3)*u(3); % EP4
dx( 4) = -k(2)*x(4)*u(1)-k(3)*x(4)*u(8); % DP1
dx( 5) = -k(8)*x(5)*u(9); % P2Y12
dx( 6) = k(8)*x(5)*u(9); % P2Y12_act
dx( 7) = k(1)*x(1)*u(2); % IP_act
dx( 8) = k(2)*x(4)*u(1); % DP1_act
dx( 9) = k(3)*x(4)*u(8); % DP1_BWA
dx(10) = k(4)*x(2)*u(1)+k(5)*x(2)*u(7); % EP3_act
dx(11) = k(6)*x(2)*u(6); % EP3_L798
dx(12) = k(7)*x(3)*u(1); % EP4_act
dx(13) = k(9)*x(3)*u(3); % EP4_L161
dx(14) = -(x(14)*((x(7)*k(16))+(x(8)*k(17))+(x(12)*k(19))))/(1+(k(18)*x(10))+(k(20)*x(6)))+k(13)*x(15)-k(15)*x(14)*u(4); % AC
dx(15) = (x(14)*((x(7)*k(16))+(x(8)*k(17))+(x(12)*k(19))))/(1+(k(18)*x(10))+(k(20)*x(6)))-k(13)*x(15); % aAC
dx(16) = k(15)*x(14)*u(4); % Fors_AC
dx(17) = (k(10)*k(11)*x(15))/((k(12)+k(10))*(1+(x(27)/k(14))))+(k(10)*k(11)*x(16))/((k(12)+k(10))*(1+(x(27)/k(14))))-k(30)*x(17)*x(25)-k(30)*x(17)*x(28)-k(30)*x(17)*x(29)-k(30)*x(17)*x(30)+k(31)*x(31)+(k(31)*x(30))+k(31)*x(29)+k(31)*x(28)+2.0*(k(33)*x(32))-((x(17)*k(22)*x(22))/(k(23)+x(17)))-(x(17)*k(24)*x(24))/(k(25)+x(17)); % cAMP
dx(18) = (x(17)*k(22)*x(22))/(k(23)+x(17))+(x(17)*k(24)*x(24))/(k(25)+x(17)); % AMP
dx(19) = -(x(19)*k(28)*x(27))/(k(29)+x(19))+k(21)*x(20); % VASP
dx(20) = (x(19)*k(28)*x(27))/(k(29)+x(19))-k(21)*x(20); % pVASP
dx(21) = -(x(21)*k(28)*x(27))/(k(29)+x(21))+k(26)*x(22)-k(27)*x(21)*u(5); % PDE3
dx(22) = (x(21)*k(28)*x(27))/(k(29)+x(21))-k(26)*x(22); % aPDE3
dx(23) = k(27)*x(21)*u(5); % iPDE3
dx(24) = 0;              % PDE2
dx(25) = -k(30)*x(17)*x(25)+k(31)*x(28)+k(36)*x(33)+k(34)*x(26)*x(26)*x(27)*x(27); % PKA
dx(26) = k(33)*x(32)+k(37)*x(37)-2.0*k(34)*x(26)*x(26)*x(27)*x(27); % R
dx(27) = 2.0*k(32)*x(31)+2.0*k(32)*x(36)-2.0*k(34)*x(26)*x(26)*x(27)*x(27); % C
dx(28) = k(30)*x(17)*x(25)-k(30)*x(17)*x(28)+k(31)*x(29)-k(31)*x(28); % PKA_cAMP
dx(29) = k(30)*x(17)*x(28)-k(30)*x(17)*x(29)+k(31)*x(30)-k(31)*x(29); % PKA_cAMP_cAMP
dx(30) = k(30)*x(17)*x(29)-k(30)*x(17)*x(30)+k(31)*x(31)-k(31)*x(30); % PKA_cAMP_cAMP_cAMP
dx(31) = k(30)*x(17)*x(30)-k(31)*x(31)-k(32)*x(31); % PKA_cAMP_cAMP_cAMP_cAMP
dx(32) = 2.0*k(32)*x(31)-k(33)*x(32); % R_cAMP_cAMP
dx(33) = -k(35)*x(33)*u(10)+k(36)*x(34)-k(36)*x(33); % PKA_cBIMPS
dx(34) = k(35)*x(33)*u(10)-k(35)*x(34)*u(10)+k(36)*x(35)-k(36)*x(34); % PKA_cBIMPS_cBIMPS
dx(35) = k(35)*x(34)*u(10)-k(35)*x(35)*u(10)+k(36)*x(36)-k(36)*x(35); % PKA_cBIMPS_cBIMPS_cBIMPS
dx(36) = k(35)*x(35)*u(10)-k(36)*x(36)-k(32)*x(36); % PKA_cBIMPS_cBIMPS_cBIMPS_cBIMPS
dx(37) = 2.0*k(32)*x(36)-k(37)*x(37); % R_cBIMPS_cBIMPS

